In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv('energydata_complete.csv')
df.shape

(19735, 29)

In [3]:
df.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   date         19735 non-null  object 
 1   Appliances   19735 non-null  int64  
 2   lights       19735 non-null  int64  
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9  

In [5]:
df.describe()

Appliances        lights            T1          RH_1            T2  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      97.694958      3.801875     21.686571     40.259739     20.341219   
std      102.524891      7.935988      1.606066      3.979299      2.192974   
min       10.000000      0.000000     16.790000     27.023333     16.100000   
25%       50.000000      0.000000     20.760000     37.333333     18.790000   
50%       60.000000      0.000000     21.600000     39.656667     20.000000   
75%      100.000000      0.000000     22.600000     43.066667     21.500000   
max     1080.000000     70.000000     26.260000     63.360000     29.856667   

               RH_2            T3          RH_3            T4          RH_4  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      40.420420     22.267611     39.242500     20.855335     39.026904   
std        4.069813      2.006111      3.254576      2.042884      4.341321   
min       20.463333     17.200000     28.766667     15.100000     27.660000   
25%       37.900000     20.790000     36.900000     19.530000     35.530000   
50%       40.500000     22.100000     38.530000     20.666667     38.400000   
75%       43.260000     23.290000     41.760000     22.100000     42.156667   
max       56.026667     29.236000     50.163333     26.200000     51.090000   

       ...            T9          RH_9         T_out   Press_mm_hg  \
count  ...  19735.000000  19735.000000  19735.000000  19735.000000   
mean   ...     19.485828     41.552401      7.411665    755.522602   
std    ...      2.014712      4.151497      5.317409      7.399441   
min    ...     14.890000     29.166667     -5.000000    729.300000   
25%    ...     18.000000     38.500000      3.666667    750.933333   
50%    ...     19.390000     40.900000      6.916667    756.100000   
75%    ...     20.600000     44.338095     10.408333    760.933333   
max    ...     24.500000     53.326667     26.100000    772.300000   

             RH_out     Windspeed    Visibility     Tdewpoint           rv1  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      79.750418      4.039752     38.330834      3.760707     24.988033   
std       14.901088      2.451221     11.794719      4.194648     14.496634   
min       24.000000      0.000000      1.000000     -6.600000      0.005322   
25%       70.333333      2.000000     29.000000      0.900000     12.497889   
50%       83.666667      3.666667     40.000000      3.433333     24.897653   
75%       91.666667      5.500000     40.000000      6.566667     37.583769   
max      100.000000     14.000000     66.000000     15.500000     49.996530   

                rv2  
count  19735.000000  
mean      24.988033  
std       14.496634  
min        0.005322  
25%       12.497889  
50%       24.897653  
75%       37.583769  
max       49.996530  

[8 rows x 28 columns]

In [6]:
df.isnull().sum()

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [7]:
df.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [8]:
df.corr()

Appliances    lights        T1      RH_1        T2      RH_2  \
Appliances     1.000000  0.197278  0.055447  0.086031  0.120073 -0.060465   
lights         0.197278  1.000000 -0.023528  0.106968 -0.005622  0.050985   
T1             0.055447 -0.023528  1.000000  0.164006  0.836834 -0.002509   
RH_1           0.086031  0.106968  0.164006  1.000000  0.269839  0.797535   
T2             0.120073 -0.005622  0.836834  0.269839  1.000000 -0.165610   
RH_2          -0.060465  0.050985 -0.002509  0.797535 -0.165610  1.000000   
T3             0.085060 -0.097393  0.892402  0.253230  0.735245  0.137319   
RH_3           0.036292  0.131161 -0.028550  0.844677  0.121497  0.678326   
T4             0.040281 -0.008859  0.877001  0.106180  0.762066 -0.047304   
RH_4           0.016965  0.114936  0.097861  0.880359  0.231563  0.721435   
T5             0.019760 -0.078745  0.885247  0.205797  0.720550  0.110409   
RH_5           0.006955  0.141233 -0.014782  0.303258  0.029595  0.250271   
T6             0.117638 -0.079029  0.654769  0.316141  0.801186 -0.009670   
RH_6          -0.083178  0.153756 -0.615045  0.245126 -0.580372  0.389933   
T7             0.025801 -0.135347  0.838705  0.021397  0.663660 -0.051422   
RH_7          -0.055642  0.035069  0.135182  0.801122  0.229212  0.690584   
T8             0.039572 -0.071458  0.825413 -0.030053  0.578191 -0.041023   
RH_8          -0.094039  0.012915 -0.006441  0.736196  0.068534  0.679777   
T9             0.010010 -0.157592  0.844777  0.115263  0.675535  0.054544   
RH_9          -0.051462 -0.008766  0.071756  0.764001  0.157346  0.676467   
T_out          0.099155 -0.074424  0.682846  0.340767  0.792255  0.033674   
Press_mm_hg   -0.034885 -0.010576 -0.150574 -0.293957 -0.133028 -0.255646   
RH_out        -0.152282  0.068543 -0.345481  0.274126 -0.505291  0.584911   
Windspeed      0.087122  0.060281 -0.087654  0.204932  0.052495  0.069190   
Visibility     0.000230  0.020038 -0.076210 -0.021057 -0.069721 -0.005368   
Tdewpoint      0.015353 -0.036322  0.571309  0.639106  0.582602  0.499152   
rv1           -0.011145  0.000521 -0.006203 -0.000699 -0.011087  0.006275   
rv2           -0.011145  0.000521 -0.006203 -0.000699 -0.011087  0.006275   

                   T3      RH_3        T4      RH_4  ...        T9      RH_9  \
Appliances   0.085060  0.036292  0.040281  0.016965  ...  0.010010 -0.051462   
lights      -0.097393  0.131161 -0.008859  0.114936  ... -0.157592 -0.008766   
T1           0.892402 -0.028550  0.877001  0.097861  ...  0.844777  0.071756   
RH_1         0.253230  0.844677  0.106180  0.880359  ...  0.115263  0.764001   
T2           0.735245  0.121497  0.762066  0.231563  ...  0.675535  0.157346   
RH_2         0.137319  0.678326 -0.047304  0.721435  ...  0.054544  0.676467   
T3           1.000000 -0.011234  0.852778  0.122737  ...  0.901324  0.134602   
RH_3        -0.011234  1.000000 -0.140457  0.898978  ... -0.195270  0.833538   
T4           0.852778 -0.140457  1.000000 -0.048650  ...  0.889439 -0.025549   
RH_4         0.122737  0.898978 -0.048650  1.000000  ... -0.044518  0.856591   
T5           0.888169 -0.050062  0.871813  0.091812  ...  0.911055  0.072308   
RH_5        -0.066355  0.375422 -0.076489  0.352591  ... -0.138509  0.272197   
T6           0.686882  0.076833  0.652350  0.259047  ...  0.667177  0.184424   
RH_6        -0.647672  0.514912 -0.703149  0.392178  ... -0.738940  0.391943   
T7           0.847374 -0.250090  0.877763 -0.131204  ...  0.944776 -0.077690   
RH_7         0.172624  0.832685  0.043527  0.894301  ...  0.028055  0.858686   
T8           0.795283 -0.283228  0.796256 -0.167066  ...  0.869338 -0.156820   
RH_8         0.044427  0.828822 -0.095192  0.847259  ... -0.113014  0.855812   
T9           0.901324 -0.195270  0.889439 -0.044518  ...  1.000000 -0.008683   
RH_9         0.134602  0.833538 -0.025549  0.856591  ... -0.008683  1.000000   
T_out        0.699417  0.118207  0.663478  0.293289  ...  0.668220  0.223270   
Press_mm_hg -0.1899

Question 12
From the dataset, fit a linear model on the relationship between the temperature in the living room in Celsius (x = T2)
and the temperature outside the building (y = T6). What is the R^2 value in two d.p.?

In [16]:
X = df['T2']
y = df['T6']
print(X, y)

0        19.200000
1        19.200000
2        19.200000
3        19.200000
4        19.200000
           ...    
19730    25.890000
19731    25.754000
19732    25.628571
19733    25.414000
19734    25.264286
Name: T2, Length: 19735, dtype: float64 0         7.026667
1         6.833333
2         6.560000
3         6.433333
4         6.366667
           ...    
19730    24.796667
19731    24.196667
19732    23.626667
19733    22.433333
19734    21.026667
Name: T6, Length: 19735, dtype: float64


In [15]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score



In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

print(X_train, X_test)


2133     19.200000
19730    25.890000
3288     21.533333
7730     17.200000
8852     17.100000
           ...    
11284    19.390000
11964    22.000000
5390     18.200000
860      20.434000
15795    19.890000
Name: T2, Length: 15788, dtype: float64 8980     17.760000
2754     21.290000
9132     17.633333
14359    23.890000
8875     16.463333
           ...    
9815     20.100000
9925     20.890000
14088    23.133333
17356    22.764286
17547    26.200000
Name: T2, Length: 3947, dtype: float64


In [18]:
print(y_train, y_test)

2133     11.100000
19730    24.796667
3288      6.530000
7730      2.790000
8852     -0.666667
           ...    
11284     9.500000
11964    17.893333
5390     -2.090000
860       1.200000
15795    10.890000
Name: T6, Length: 15788, dtype: float64 8980      1.198571
2754      2.530000
9132     -0.266667
14359    11.160000
8875     -0.733333
           ...    
9815      6.800000
9925      8.860000
14088    13.866667
17356    13.830000
17547    23.263333
Name: T6, Length: 3947, dtype: float64


In [31]:
reg = LinearRegression()
reg.fit(X_train.values.reshape(-1,1), y_train)
print(reg.coef_)


[2.22739928]


In [34]:
y_predicted = reg.predict(X_test.values.reshape(-1,1))
y_predicted

array([ 2.15562488, 10.01834433,  1.87348764, ..., 14.12418366,
       13.30216726, 20.95487478])

In [36]:
round(r2_score(y_test, y_predicted),2)
#Answer = 0.64

0.64

Question 13
Normalize the dataset using the MinMaxScaler after removing the following columns: [“date”, “lights”]. 
The target variable is “Appliances”. Use a 70-30 train-test set split with a random state of 42 (for reproducibility). 
Run a multiple linear regression using the training set and evaluate your model on the test set.
What is the Mean Absolute Error (in two decimal places)?



In [61]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error


In [39]:
DF = df.drop(columns= ["date", "lights"])


In [41]:
DF.head()

Appliances     T1       RH_1    T2       RH_2     T3       RH_3         T4  \
0          60  19.89  47.596667  19.2  44.790000  19.79  44.730000  19.000000   
1          60  19.89  46.693333  19.2  44.722500  19.79  44.790000  19.000000   
2          50  19.89  46.300000  19.2  44.626667  19.79  44.933333  18.926667   
3          50  19.89  46.066667  19.2  44.590000  19.79  45.000000  18.890000   
4          60  19.89  46.333333  19.2  44.530000  19.79  45.000000  18.890000   

        RH_4         T5  ...         T9   RH_9     T_out  Press_mm_hg  RH_out  \
0  45.566667  17.166667  ...  17.033333  45.53  6.600000        733.5    92.0   
1  45.992500  17.166667  ...  17.066667  45.56  6.483333        733.6    92.0   
2  45.890000  17.166667  ...  17.000000  45.50  6.366667        733.7    92.0   
3  45.723333  17.166667  ...  17.000000  45.40  6.250000        733.8    92.0   
4  45.530000  17.200000  ...  17.000000  45.40  6.133333        733.9    92.0   

   Windspeed  Visibility  Tdewpoint        rv1        rv2  
0   7.000000   63.000000        5.3  13.275433  13.275433  
1   6.666667   59.166667        5.2  18.606195  18.606195  
2   6.333333   55.333333        5.1  28.642668  28.642668  
3   6.000000   51.500000        5.0  45.410389  45.410389  
4   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 27 columns]

In [49]:
X = DF.drop(columns=["Appliances"]).values
Y = DF["Appliances"].values
X


array([[19.89      , 47.59666667, 19.2       , ...,  5.3       ,
        13.27543316, 13.27543316],
       [19.89      , 46.69333333, 19.2       , ...,  5.2       ,
        18.60619498, 18.60619498],
       [19.89      , 46.3       , 19.2       , ...,  5.1       ,
        28.64266817, 28.64266817],
       ...,
       [25.5       , 46.59666667, 25.62857143, ..., 13.26666667,
        29.19911708, 29.19911708],
       [25.5       , 46.99      , 25.414     , ..., 13.23333333,
         6.32278365,  6.32278365],
       [25.5       , 46.6       , 25.26428571, ..., 13.2       ,
        34.11885059, 34.11885059]])

In [48]:
Y

array([ 60,  60,  50, ..., 270, 420, 430], dtype=int64)

In [68]:
scale_X = MinMaxScaler()
X = scale_X.fit_transform(X)

In [69]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)
print(X_train, Y_train)


[[0.49736008 0.23676727 0.12284953 ... 0.19230769 0.72455446 0.72455446]
 [0.28616684 0.48261627 0.18899927 ... 0.34238311 0.86404083 0.86404083]
 [0.42238648 0.23052931 0.0574267  ... 0.15837104 0.4995025  0.4995025 ]
 ...
 [0.36958817 0.23878543 0.15265326 ... 0.16591252 0.38138779 0.38138779]
 [0.5279831  0.23493257 0.31504725 ... 0.11463047 0.02090909 0.02090909]
 [0.47870468 0.29465187 0.27550279 ... 0.49547511 0.34907575 0.34907575]] [ 50  30  40 ...  30  80 130]


In [70]:
print(X_test, Y_test)


[[0.43294615 0.23052931 0.12066877 ... 0.29864253 0.5124281  0.5124281 ]
 [0.53854277 0.71764058 0.37727163 ... 0.35294118 0.46946581 0.46946581]
 [0.48574446 0.23328135 0.11146111 ... 0.19004525 0.00276141 0.00276141]
 ...
 [0.43681802 0.34061095 0.18899927 ... 0.51508296 0.79270322 0.79270322]
 [0.55015839 0.39097331 0.33438333 ... 0.52036199 0.60830695 0.60830695]
 [0.43294615 0.42014494 0.21322995 ... 0.74057315 0.19891132 0.19891132]] [ 40  90  50 ...  50 110  50]


In [71]:
reg = LinearRegression()
reg.fit(X_train ,Y_train)
print(reg.coef_)


[  -3.51072478  592.29486183 -252.710373   -488.66680472  310.97103712
  102.77165244   31.00966845   28.23278127  -16.75282177   17.12619362
  252.97465249   40.7120577    11.04109074  -47.73659198  109.13469841
 -168.62716102 -203.23662712  -42.58633878 -344.3898449     7.31807923
  -83.1075989    31.22594824   13.16807161  126.00077634    0.824005
    0.824005  ]


In [72]:
Y_predicted = reg.predict(X_test)

In [74]:
round(mean_absolute_error(Y_test, Y_predicted),2)
#Answer = 53.64


53.64

Question 14
What is the Residual Sum of Squares (in two decimal places)?

In [87]:
print("Residual sum of squares is : %.2f"% ((Y_predicted - Y_test) ** 2).sum())

Residual sum of squares is : 51918501.21


Question 15
What is the Root Mean Squared Error (in three decimal places)?


In [88]:
from sklearn.metrics import mean_squared_error


In [93]:
RMS = mean_squared_error(Y_test, Y_predicted)
round(RMS, 3)
#Answer = 8768.536


8768.536

Question 16
What is the Coefficient of Determination (in two decimal places)?

In [94]:
from sklearn.metrics import r2_score


In [95]:
print("Coefficient of Determination is: ", round(r2_score(Y_test,Y_predicted),2))
#Answer = 0.15

Coefficient of Determination is:  0.15


Question no. 17:
Obtain the feature weights from your linear model above. Which features have the lowest and highest weights respectively?

Question 18
Train a ridge regression model with an alpha value of 0.4. Is there any change to the root mean squared error (RMSE) when evaluated on the test set?

In [97]:
from sklearn.linear_model import Ridge

In [102]:
Rreg = Ridge(alpha=0.4)
Rreg.fit(X_train, Y_train)


Ridge(alpha=0.4)

In [103]:
Y_pred_ridge = Rreg.predict(X_test)

In [108]:
RMS = mean_squared_error(Y_test, Y_pred_ridge)
print(round(RMS,3))


8772.425


Question no. 19:
Train a lasso regression model with an alpha value of 0.001 and obtain the new feature weights with it. How many of the features have non-zero feature weights?

In [101]:
from sklearn import linear_model

In [106]:
Lreg = linear_model.Lasso(alpha=0.001)
Lreg.fit(X_train,Y_train)


Lasso(alpha=0.001)

In [107]:
Y_pred_lasso = Lreg.predict(X_test)

Question no. 20:
What is the new RMSE with the lasso regression? (Answer should be in three (3) decimal places)

In [109]:
RMS = mean_squared_error(Y_test, Y_pred_lasso)
round(RMS,3)


8768.576